'use client'

import { useState, useRef, useEffect } from 'react'
import { produce } from 'immer'
import ReactMarkdown from 'react-markdown'
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import { Sparkles, Send, X, Trash2 } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { ScrollArea } from '@/components/ui/scroll-area'
import { cn } from '@/lib/utils'
import { submitChat, getChatHistory, clearChatHistory } from '@/lib/ai/actions'
import { toast } from 'sonner'
import { useNavigate } from 'react-router-dom'
import { AnimatePresence, motion } from 'framer-motion'
import { createRoom } from '@/components/rooms/actions'

import { useAI } from '@/lib/ai-context'

type Message = {
  role: 'user' | 'model'
  content: { text: string }[]
}
import { usePresence } from '@/components/dashboard/presence-provider'

export function AIChat(): React.JSX.Element {
  const navigate = useNavigate()
  const { isOpen, setIsOpen, status, setStatus } = useAI()
  const { onlineUsers } = usePresence()
  const [messages, setMessages] = useState<Message[]>([])
  const [input, setInput] = useState('')
  const [isLoading, setIsLoading] = useState(false)
  const [showClearConfirm, setShowClearConfirm] = useState(false)
  const scrollEndRef = useRef<HTMLDivElement>(null)

  useEffect(() => {
    const loadHistory = async (): Promise<void> => {
      try {
        const history = (await getChatHistory()) as Message[]
        if (history && history.length > 0) {
          setMessages(history)
        }
        // eslint-disable-next-line @typescript-eslint/no-unused-vars
      } catch (e) {
        console.error('Failed to load history')
      }
    }
    loadHistory()
  }, [])

  useEffect(() => {
    if (scrollEndRef.current) {
      scrollEndRef.current.scrollIntoView({ behavior: 'smooth' })
    }
  }, [messages, isOpen])

  const handleSend = async (): Promise<void> => {
    if (!input.trim()) return

    setStatus('thinking')
    const userMessage: Message = { role: 'user', content: [{ text: input }] }
    setMessages(
      produce((draft) => {
        draft.push(userMessage)
      })
    )
    setInput('')
    setIsLoading(true)

    try {
      const history = messages.slice(-10)
      const activeUserIds = Array.from(onlineUsers)
      const result = await submitChat(input, history, activeUserIds)

      if (result.error) {
        setStatus('error')
        toast.error('VIRE is having trouble thinking right now.')
        return
      }

      setStatus('online')
      if (result.response) {
        let responseText = result.response
        
        // Parse Commands
        const commandRegex = /<<<COMMAND:(.*?)>>>/
        const commandMatch = responseText.match(commandRegex)
        
        if (commandMatch && commandMatch[1]) {
          try {
            const command = JSON.parse(commandMatch[1])
            if (command.type === 'navigate_app' && command.path) {
              navigate(command.path)
              toast.success(`VIRE is navigating to ${command.path}`)
              setIsOpen(false)
            } else if (command.type === 'create_room') {
              const safeName = command.roomName || 'AI Room'
              const uniqueName = `${safeName} ${Math.random().toString(36).substring(2, 6).toUpperCase()}`
              
              toast.info(`VIRE is creating room: ${uniqueName}...`)
              const formData = new FormData()
              formData.append('name', uniqueName)
              formData.append('description', 'A room autonomously generated by VIRE AI.')
              formData.append('isPublic', 'on')
              
              try {
                const res = await createRoom(formData)
                if (res.success && res.redirect) {
                  navigate(res.redirect)
                  toast.success('Room created successfully!')
                  setIsOpen(false)
                } else {
                  console.error('Room Creation Failed:', res.error)
                  toast.error(res.error || 'Failed to create room.')
                }
              } catch (err: any) {
                console.error('Exception during room creation:', err)
                toast.error(err.message || 'An unexpected error occurred.')
              }
            } else {
              toast.success('AI executed a command.')
            }
            // Remove command from text
            responseText = responseText.replace(commandRegex, '').trim()
          } catch (e) {
            console.error('Failed to parse AI command', e)
          }
        }

        if (responseText) {
          const aiMessage: Message = {
            role: 'model',
            content: [{ text: responseText }]
          }
          setMessages(
            produce((draft) => {
              draft.push(aiMessage)
            })
          )
        }
      }
      // eslint-disable-next-line @typescript-eslint/no-unused-vars
    } catch (e) {
      setStatus('error')
      toast.error('Connection error.')
    } finally {
      setIsLoading(false)
    }
  }

  return (
    <>
      <AnimatePresence>
        {/* Floating Trigger Button */}
        {!isOpen && (
          <motion.div
            initial={{ scale: 0, opacity: 0 }}
            animate={{ scale: 1, opacity: 1 }}
            exit={{ scale: 0, opacity: 0 }}
            className="fixed bottom-20 right-4 md:bottom-6 md:right-6 z-[60]"
          >
            <Button
              size="icon"
              className={cn(
                'h-12 w-12 md:h-14 md:w-14 rounded-full shadow-lg transition-all duration-300 border border-white/20',
                status === 'error'
                  ? 'bg-red-500/20 hover:bg-red-500/30 shadow-red-500/20'
                  : 'bg-gradient-to-tr from-violet-600 to-fuchsia-600 shadow-[0_0_20px_rgba(168,85,247,0.5)] hover:scale-105'
              )}
              onClick={() => setIsOpen(true)}
            >
              <Sparkles
                className={cn(
                  'w-5 h-5 md:w-6 md:h-6 text-white',
                  status === 'online' && 'animate-pulse'
                )}
              />
            </Button>
          </motion.div>
        )}

        {/* Chat Window */}
        {isOpen && (
          <motion.div
            initial={{ opacity: 0, y: '100%', scale: 0.95 }}
            animate={{ opacity: 1, y: 0, scale: 1 }}
            exit={{ opacity: 0, y: '100%', scale: 0.95 }}
            transition={{ type: 'spring', damping: 25, stiffness: 200 }}
            className="fixed z-50 flex flex-col overflow-hidden border border-white/10 bg-black/80 backdrop-blur-2xl shadow-[0_-20px_50px_-10px_rgba(0,0,0,0.5)]
              bottom-0 left-0 w-full h-[85vh] rounded-t-2xl rounded-b-none
              md:bottom-4 md:left-auto md:right-4 md:w-96 md:h-[600px] md:max-h-[85vh] md:rounded-2xl"
          >
            {/* Header */}
            <div className="p-4 border-b border-white/5 bg-white/5 flex items-center justify-between backdrop-blur-md sticky top-0 z-10">
              <div className="flex items-center gap-3">
                <div className="relative">
                  <div
                    className={cn(
                      'w-10 h-10 rounded-full flex items-center justify-center border border-white/10 transition-colors',
                      status === 'error'
                        ? 'bg-red-500/20'
                        : 'bg-gradient-to-br from-violet-500/20 to-fuchsia-500/20'
                    )}
                  >
                    <Sparkles
                      className={cn(
                        'w-5 h-5',
                        status === 'error' ? 'text-red-400' : 'text-violet-400'
                      )}
                    />
                  </div>
                  <span
                    className={cn(
                      'absolute bottom-0 right-0 w-2.5 h-2.5 border-2 border-black rounded-full animate-pulse',
                      status === 'error'
                        ? 'bg-red-500 shadow-[0_0_8px_rgba(239,68,68,0.6)]'
                        : 'bg-green-500 shadow-[0_0_8px_rgba(34,197,94,0.6)]'
                    )}
                  ></span>
                </div>
                <div>
                  <h3 className="font-bold text-sm text-white tracking-wide">VIRE AI</h3>
                  <p
                    className={cn(
                      'text-[10px] font-medium',
                      status === 'error' ? 'text-red-400' : 'text-zinc-400'
                    )}
                  >
                    {status === 'error'
                      ? 'Connection Failed'
                      : status === 'thinking'
                        ? 'Thinking...'
                        : 'System Online'}
                  </p>
                </div>
              </div>

              <div className="flex items-center gap-1">
                <Button
                  variant={showClearConfirm ? 'destructive' : 'ghost'}
                  size={showClearConfirm ? 'sm' : 'icon'}
                  className={cn(
                    'transition-all duration-300 group',
                    showClearConfirm
                      ? 'w-auto px-3 bg-red-500/20 text-red-400 hover:bg-red-500/30 border border-red-500/30'
                      : 'h-8 w-8 text-zinc-400 hover:text-red-400 hover:bg-red-500/10'
                  )}
                  onClick={async (e) => {
                    e.preventDefault()
                    if (!showClearConfirm) {
                      setShowClearConfirm(true)
                      setTimeout(() => setShowClearConfirm(false), 3000)
                      return
                    }
                    const res = await clearChatHistory()
                    if (res.success) {
                      setMessages([])
                      toast.success('Memory Wiped')
                    } else {
                      toast.error('Deletion Failed')
                    }
                    setShowClearConfirm(false)
                  }}
                >
                  {showClearConfirm ? (
                    <span className="text-xs font-bold">CONFIRM</span>
                  ) : (
                    <Trash2 className="w-4 h-4" />
                  )}
                </Button>
                <Button
                  variant="ghost"
                  size="icon"
                  className="h-8 w-8 text-zinc-400 hover:text-white hover:bg-white/10 rounded-full transition-colors"
                  onClick={() => setIsOpen(false)}
                >
                  <X className="w-4 h-4" />
                </Button>
              </div>
            </div>

            {/* Messages */}
            <ScrollArea className="flex-1 min-h-0 bg-transparent">
              <div className="flex flex-col gap-6 p-5">
                {messages.length === 0 && (
                  <div className="flex flex-col items-center justify-center h-full mt-20 space-y-4 opacity-50">
                    <Sparkles className="w-12 h-12 text-violet-400/50" />
                    <p className="text-sm text-zinc-500 text-center max-w-[200px]">
                      {/* eslint-disable-next-line react/no-unescaped-entities */}
                      "I am listening. What's on your mind?"
                    </p>
                  </div>
                )}

                {messages.map((msg, idx) => (
                  <motion.div
                    initial={{ opacity: 0, y: 10, scale: 0.95 }}
                    animate={{ opacity: 1, y: 0, scale: 1 }}
                    key={idx}
                    className={cn(
                      'flex w-full',
                      msg.role === 'user' ? 'justify-end' : 'justify-start'
                    )}
                  >
                    <div
                      className={cn(
                        'max-w-[85%] rounded-2xl px-5 py-3 text-sm leading-relaxed shadow-lg backdrop-blur-sm overflow-hidden',
                        msg.role === 'user'
                          ? 'bg-gradient-to-br from-violet-600 to-indigo-600 text-white rounded-br-sm shadow-violet-900/20 border border-white/10'
                          : 'bg-zinc-900/80 text-zinc-100 rounded-bl-sm border border-white/5 shadow-black/20'
                      )}
                    >
                      <div
                        className={cn(
                          'prose prose-invert max-w-none prose-p:leading-relaxed prose-pre:bg-black/50 prose-pre:p-2 prose-pre:rounded-lg',
                          msg.role === 'user' && 'prose-p:text-white'
                        )}
                      >
                        <ReactMarkdown
                          components={{
                            p: ({ children }) => <p className="mb-2 last:mb-0">{children}</p>
                          }}
                        >
                          {msg.content[0].text}
                        </ReactMarkdown>
                      </div>
                    </div>
                  </motion.div>
                ))}

                {isLoading && (
                  <motion.div
                    initial={{ opacity: 0 }}
                    animate={{ opacity: 1 }}
                    className="flex justify-start w-full"
                  >
                    <div className="bg-zinc-900/50 border border-white/5 rounded-2xl rounded-bl-sm px-4 py-3 flex gap-1.5 items-center">
                      <span className="text-[10px] text-zinc-500 mr-2 font-mono">THINKING</span>
                      <div className="w-1.5 h-1.5 bg-violet-500 rounded-full animate-[bounce_1s_infinite_-0.3s]"></div>
                      <div className="w-1.5 h-1.5 bg-violet-500 rounded-full animate-[bounce_1s_infinite_-0.15s]"></div>
                      <div className="w-1.5 h-1.5 bg-violet-500 rounded-full animate-[bounce_1s_infinite]"></div>
                    </div>
                  </motion.div>
                )}
                <div ref={scrollEndRef} />
              </div>
            </ScrollArea>

            {/* Input Area */}
            <div className="p-4 bg-gradient-to-t from-black/80 to-transparent">
              <div className="relative group">
                <div className="absolute -inset-0.5 bg-gradient-to-r from-violet-600 to-fuchsia-600 rounded-full opacity-30 group-focus-within:opacity-100 transition duration-500 blur"></div>
                <div className="relative flex gap-2 bg-black/90 rounded-full p-1.5 border border-white/10 items-center">
                  <Input
                    placeholder="Type a message..."
                    value={input}
                    onChange={(e) => setInput(e.target.value)}
                    onKeyDown={(e) => e.key === 'Enter' && handleSend()}
                    className="flex-1 bg-transparent border-0 focus-visible:ring-0 text-sm h-10 px-4 placeholder:text-zinc-600 text-white"
                    disabled={isLoading}
                  />
                  <Button
                    size="icon"
                    className="rounded-full w-9 h-9 bg-zinc-800 hover:bg-zinc-700 text-zinc-400 group-focus-within:bg-violet-600 group-focus-within:text-white transition-all duration-300"
                    onClick={handleSend}
                    disabled={isLoading || !input.trim()}
                  >
                    <Send className="w-4 h-4" />
                  </Button>
                </div>
              </div>
              <div className="flex justify-center mt-3">
                <p className="text-[10px] text-zinc-600 font-mono tracking-widest uppercase opacity-50">
                  V I R E &nbsp; I N T E L L I G E N C E
                </p>
              </div>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </>
  )
}
